version: '3.8'

services:
  # Development overrides
  app:
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npx prisma generate && npx prisma db push --accept-data-loss && npm run dev"

  # Development database with exposed ports
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres123

  # Development Redis
  redis:
    ports:
      - "6379:6379"

  # Development Prisma Studio
  prisma-studio:
    command: sh -c "npm install && npx prisma generate && npx prisma studio --hostname 0.0.0.0 --port 5555"
